# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SIX FAMILIES
email: 666families@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    six families is a collection of musicians that aims to create opportunities for both performers and listeners to participate in honest, thoughtful, and compelling experiences relating to sound/silence/song.. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "saxopon.github.io" # the base hostname & protocol for your site
twitter_username: 6families
github_username:  6families

# Build settings
markdown: kramdown
